### ISSUE TITLE
Initial Discussion

### ISSUE THREAD

**Issue by adammhaile** [adafruit/Adafruit_CircuitPython_SK9822#1]
@kattni @tannewt 
Alright, so I'll get things copied over from the DotStar library shortly.
Some questions to start:

- You mentioned a PixelBuffer class being added. Any idea if that will be merged soon and then I could just based this new module off that work from the start? Or should I just copy over what I have now?
- What do you want to do about the attribute count pylint warning?
- Any other things you would like me to change with my original implementation?

**Comment by kattni** [comment]
- There's no ETA on the PixelBuf class being added, so for now let's go with what we have and we'll make changes when we have the option.
- I wasn't sure whether you would need all of the same attributes if the library is specific to the SK9822 LEDs vs including broader support for everything. If you're still running into that issue, we can consider doing a local `# pylint: disable=warning-name` followed by an `enable` if it makes sense. The `pylint` warnings are a guideline, not always hard rules. There are plenty of situations where `disable` is warranted. If you feel the way you've written it is the most reasonable way to do it, then it's a valid option.
- We're pretty happy with the current API (which is used across NeoPixel and Pixie as well) so since you're basically following that, I'd say you're doing pretty well. We can give it another look after you put in the PR.

Let me know if you need anything else!

**Comment by dherrada** [comment]
@kattni Is this something that would be useful for me to work on, or is there another library for this that has code in it?

**Comment by kattni** [comment]
@dherrada The library is already written, but as Adafruit does not carry the product, we have no way to test it or maintain it. So it was suggested that it be submitted to the Community Bundle instead. This issue can be closed for now. There is a chance Adafruit may eventually carry these so I don't want to delete the repo.
